version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ads-market-bot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
