version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: ads_market_db
    environment:
      POSTGRES_DB: ads-market-bot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ads_market_net
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: ads_market_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - ads_market_net
    restart: always

volumes:
  postgres_data:

networks:
  ads_market_net: